
CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LECTURE (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LECTURE_SCHEDULE (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LECTURE_ID INTEGER NOT NULL,
    RECRUIT_COUNT INTEGER NOT NULL,
    APPLY_COUNT INTEGER NOT NULL DEFAULT 0,
    OPEN_DATE DATETIME NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LECTURE_APPLY (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LECTURE_SCHEDULE_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LECTURE_APPLY_HISTORY (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LECTURE_APPLY_ID INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);